### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by mr-wildcard** [mr-wildcard/yuna.work#10]
# QA

## General
- [x] text content
- [x] clean up commented html code
- [x] page h1 margin top on xl
- [x] allow pinching screen? `<meta name="viewport" content="width=device-width, initial-scale=1.0" />`
- [x] open graph
- [x] favicon
- [x] open graph image

## Header
- [x] hover style nav items
- [x] mobile: scroll y

## Footer
- [x] hover style nav items

## Homepage:
- [x] hero: title & paragraph widths on lg? reduce number of dots?

## Collaborations
- [ ] client logos image quality
- [x] at which breakpoint project layout switch from mobile to desktop
- [x] projects screenshots alts
- [x] project testimonial summary width on mobile
- [x] dots left side of projects
- [x] project summary: chevron size
- [x] project screenshots correct size 635px wide

## About
- [x] does seperators between "Fiertés professionnelles" remains in `container`?

### 404
- [x] create page

---

### Homepage
- [x] xs
- [x] sm
- [x] md
- [x] lg
- [x] xl
- [x] 2xl

### Collabs
- [x] xs
- [x] sm
- [x] md
- [x] lg
- [x] xl
- [x] 2xl

### A propos
- [x] xs
- [x] sm
- [x] md
- [x] lg
- [x] xl
- [x] 2xl

### Plan du site
- [x] xs
- [x] sm
- [x] md
- [x] lg
- [x] xl
- [x] 2xl

### Mentions légales
- [x] xs
- [x] sm
- [x] md
- [x] lg
- [x] xl
- [x] 2xl

**Comment by yuna-orsini** [comment]
### Collaborations : 

- [ ] dots du haut de page : 5 lignes et non 4
- [ ] dots en bas de page : 5 lignes et non 6
